name: Deploy Van Login

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Deploy to Server (Source)
        uses: easingthemes/ssh-deploy@main
        with:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: "-rlgoDzvc -i"
            SOURCE: "src/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ vars.PATH_TO_DEPLOY }}
            SCRIPT_BEFORE: |
              whoami
              ls -la  ${{ vars.PATH_TO_DEPLOY }}
            SCRIPT_AFTER: |
              whoami
              ls -la  ${{ vars.PATH_TO_DEPLOY }}
              echo $RSYNC_STDOUT
      
      - name: Deploy to Server (Infra)
        uses: easingthemes/ssh-deploy@main
        with:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: "-rlgoDzvc -i"
            SOURCE: "infra/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ vars.PATH_TO_DEPLOY_INFRA }}
            SCRIPT_BEFORE: |
              whoami
              ls -la  ${{ vars.PATH_TO_DEPLOY_INFRA }}
            SCRIPT_AFTER: |
              whoami
              ls -la  ${{ vars.PATH_TO_DEPLOY_INFRA }}
              echo $RSYNC_STDOUT

